import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Topo from '@/componentes/TOPO'
import Capa from '@/componentes/secaoCapa'
import Produto from '@/componentes/SecaoProduto'
import Sobre from '@/componentes/SecaoSobre'
import Contato from '@/componentes/SecaoContato'
import Rodape from '@/componentes/Rodape'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Topo/>
      <Capa/>
      <Produto/>
      <Sobre/>
      <Contato/>
     <Rodape/>

    </>
  );
}
